### ISSUE TITLE
是否有兴趣参与smart-doc贡献

### ISSUE THREAD

**Issue by shalousun** [Tanky-Zhang/big-smart-doc-maven-plugin#1]
我是smart-doc作者，发现你实现了Grpc功能，有没有兴趣加入到社区参与贡献

**Comment by Tanky-Zhang** [comment]
非常荣幸收到您的邀请，我的smart-doc的gRPC文档生成功能其实有一些缺陷的，现在也仅仅是在组内使用。因为我实现的时候采用了一种取巧的方式，借助了三方的protoc-gen-doc实现，并没有重写整个生成过程，我也一直有一个想法，重写整个gRPC文档生成过程，当然，我也非常愿意能够加入社区进行贡献一起做点事情。
也可以加下微信一起探讨，我的微信是AO_TE_MAN007




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tanky-Zhang/big-smart-doc-maven-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 上午10:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Tanky-Zhang/big-smart-doc-maven-plugin] 是否有兴趣参与smart-doc贡献 (Issue #1)





 
我是smart-doc作者，发现你实现了Grpc功能，有没有兴趣加入到社区参与贡献
